version: '3.9'

services:
  node:
    container_name: node
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src/:/usr/src/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
